language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: 2WtTAp0ajJzJUKSXSMrFhVf+q+FuvFzn/hyJQ1tkqdAvb0FYmcLqfA4TDHteEdOB/PyIWe6/lHnRFQRsefNn9rnARpxYMgYQone5PeS88TDdtAppsDwTDGB2Bjep4sdBMrUsZwi/n6ePyOvLVn0RdIxkDq5S0B59ET9r6/RLiGSFU1jZYFxjA6c0M3CfiUcr5SN2pvzmF6bJ5lmhiPGEEgHtPCA3oFBI9IsJvsaOZ2BOOOXHndyMTrbh3bDc5hQ81LXoRLGyIHc3g37b683Ai5sbhqPvO7GFV1kKepLT2BzmofqnjG5NEtEf4vL+T+j/uLCAT88ywxLGbyq3quvm/M5XD28cSD3QfZqbNPoPaLrckfeYO7WDDkHuOSzEEiF3KgsZ/jW2ifZo8xnZMjFD7ynWARrW6ywzs6urWZ8AJdSRQbug5jUenIlwOCeDiqQL8g0FUvAQ/QtT8YZfH4+nJ74ypLf2MgR/wJLSJa1VKzYfJJGJTY8nwzLL9ZNpcEn70heOgprQ0dCbvjOYAYA70rEznzdWMtk8s7mC9MBsoXCprRFwq4lyjDt0ef3ZzV+6qnYGldIZOoOnrClaV9YNSnm4/MwvDp7FHGg2lJ65o+qW02dbJXD9496n+XCdgAqSK9xmFwJHikLXuLAfvVg+VBEqGX0YBO0alaotO5KYISk=
  app:
    master: stacktest4
