language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: QOaEvuBNRB9luJHqLrHpcIl3mjbHadq6Eblr5TU+cZfEOGK8UYDd/xiYazn3H8VbBfWzeY/gMSlRoE17Stlw0H/NWky+HOzxgjp17OEAAeC51hdwYKeYpcFIZDbPL2Gq612RE7bKzTVrdGS3FMvZABfqjUcXsCa7YF8/qSlFakYfGAo4sqvwWYfQYD+Pt4FSmqqXiZokNA4fgO+g5bd3D+HDtAWN6g7AMHQI+aH+rN+274nIc3ejUg/fOnxXWai8UTe6ONVxOVCi6HNChVYTXMSXW8zM7epwagzsjdWJK/PXmZ1/kexCCu0pVqvsuvkgdKGewr2wkHBaFoRMYVC4OjcZ6b2ibwvoADMI+mVyF/pW/iSSAiIGMRsGDjSWqXiAjUTE1M9hg58vCoeW2Zlj+P3cZlylBOjt7eosM0vRNG2RGOe4Vha68OcGZ/gFPsf3HQDGWhZ32Wm0e0umpZIf76X87UVYqbjEylQYmOGj9/4oFPXhlgwBt08aCPw+Fr47/EWBjEG3duFLgUZ5kNJdfK5u+ga0+GZ6P+T50CHWBnKlDm5lYcDbTAm/K7ok+HRlskHpO2wI+VTVZdHULquu7vZ1hN1zc1DfRm2R0GXdveUcoVDh3poDg6dHzomhH15NKeZ5OZQh/clVSumx1bvmIs1Sf8CRPoJsNHe/EE0Diew=
  app:
    master: stacktest4
