language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: Txr4kpcE224R4nq3kNKrpksu1/bCKMBzpkKyMX/3Yf5uDedpr/ta5qMgd0kbi2XGS/xhdQK1bOSly9tntvMIDxdK8Vm3t9RShUaneSKNJrnAV3XJiN+BwCeQ4SNZXbAuNeryXYUcDaT2M/Qnfb/msVj0HJFXxHHMzW0i2vgDT1WPpFmmnwUZq8jpwS4H+vj/07KlI3aJPVs1eXpFMThtxapUZ+hH5dYJhDklxNyP7eYBaLLlpLk6iySOMCgYsOR4Aianuu4w/UpoLijNu46aLxDxnDoIaM9nvmbDpdaPbnbGJLksYZ5SOegtPwy8MUcQjnVAO0l2sLhnUd3etdOCmBQyAycldmLNeMZTeZTEBm5ygl2p5GFGaYimRVwnPvx7JQ6p2RmPmyk63uFb6AZJvTTyBfMUyKhDb76B1/8lZ3WRd0prI6ofAWlSGcaPbtz3ylYYbESSweDAX0A7yMHVkuSKJW/YiXcxz2PvUMKP8rZeQwT7t9mYpxR2mcy3MhTz5lLF/qAUYwATWHCgui0Dis9brDUrkotBwMq432uIVOoAoPf08rVgJOP04Cp0hF5pN63QIJ/G53pfdTG6BA7LHRyRveHH6rTEiT3uIhfbgUDLfLXbLWWT6l2EGUJh13JKnabudDUxTofomy/2YOyfkJL+u7yhNkQwpi/ot8dweHY=
  app: stacktest4
  on:
    repo: glowlex/test
