language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
master:
    secure: Oy8ErEDiahTYJEQZ0bBoZVOs7SPHNDAgwsFjBu+aOaUAbZ5aZxyyZxVjP3JEUjD0yjdpC0UhKLHGQZFwSFthot7yQeCXk1+sWvPWzMMmaI30icySL28TRdVBXNK3r7mEPes+RkJOFurKkva8Dh/ZEqqglIT111wNdpzldXm+ds8pgxroCAmEQ6Gr1IX1w2nd2Z99PcCCA5O96H2vJuAkp1F6j/0q1SImFryKYobBCo14G9P/c0aG713+uaSr/AQUeJNt4tGzhKVY2mWZe6KSfWND1eX0eB7qaEzt7ltnIJKOL1EfYN7fHoADJsPt3xEVzPdenddyy3vvXm+FNR+CeLVAi1NBNS+gDZuZ4D6iB4FWJToBu7Yf+aRPG+KsjJ3I9frq1Oi9J2cwQIrb7WYBX/qfkakSWxycv4ukihvZNkRCv3veT43ymHkDQYFU6Kj/mEvY6uu9IjoG7XRgl2AWtbWaORTsEFP0BK4ftC4UAcO6ULnaeGcZHDu+52kk2ZM0sFaUcWvemXBB7+dl8dw1y2fPW2v4SuYRUXyha8vjENzT0vz6DxnlSVe9BhDWGnaVaQIEMNjcYZiYembm9Sq/H50TzYoXT7tvtYCE8m6L4YkJFiAI/xrSp0D5DOr72oAzHwCkM67EG4WXWvrPAgSp7g3E7LOCAIJClwgXx0mLgSk=
  app: 
  master: stacktest4

