language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: HhybvBucjYShoBXRmJStg8X7cI6DnTMUgeplI3uWV7SCEVhJZjNaeDQb025Af5cuLAf/yPXqscSXQAgpvkP/bVFU32H6KSgrbBoSJ2tkMvTSFO9h2XvHZ5l5UmCIIZeSNi0x5kVFCUoQbMBS3NDQZfI+7h8zB+E4mwbN7jC1u+hmdVEL4jJytD6zP47J2pXNvD1DrTF+g5ptpU2DJtaU3UOFwj6N2Wv7mE9pdcbL75uTVz9FZoQXkb6FCj3aXk6IM2clGqO9Q1crl5pdVkdvG4Kp75iZIDjDdfse5jjt7145X70TT6DT8CCSp+JzKVlwJ3W++8EwEXWxim6wdfaVOjCmn8hw99dZxuS4jDtTS0ePFqtkJSCPjRlxz4S1I5Jv/G/D0Zurl8DIcLBNBeuh4bWcv5tXuiCy6kjHu0zDWuobAKygojvv3/gD8ExY1bi+2caSvLn/bu+LYb7x0BDJvBC5dxNWG93Zl0RYml2EBj/4e5PTko/T0tLDzdYtli9jEFDraoIp6qeWUN8AGikw/jxdSjYXjTcVnixdTotmvToJBs3EnRBUzJr8Qi7UvMQYaUgY34KonD0h5BkdOUl00HkOrjwU6mhoUW/yGa1LchqHaCBSSCy14FMApcya/P1o6WLyCX2ZV7Hn5oyKZfWKqLoPNICnQCJSrPYzh1yJXV4=
  app:
    master: stacktest4
